version: "3.6"

services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    platform: linux/amd64
    command:
      - -F # turn fsync off for speed
      - -N 1000 # increase max connections from 100 so we can run more HGEs
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: "password" # you probably want to override this
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - psql -U "$${POSTGRES_USER:-postgres}" < /dev/null && sleep 5 && psql -U "$${POSTGRES_USER:-postgres}" < /dev/null
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 20

  cockroach:
    image: cockroachdb/cockroach:latest-v22.2
    command:
      - start-single-node
      - --insecure
      - --accept-sql-without-tls
    init: true # doesn't shut down properly without this
    ports:
      - 26257
    volumes:
      - /cockroach/cockroach-data
    healthcheck:
      test:
        - CMD-SHELL
        - cockroach sql --insecure --execute "select 1;" 
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 20
